name: unping_ui
description: Desktop & Web first flutter component library
#publish_to: none
homepage: https://unping-ui.com
repository: https://github.com/unping/unping-ui
version: 0.2.3

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ">=6.2.1 <8.0.0"
  flutter_bloc: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0


flutter:
  assets:
    - assets/fonts/
  
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
    
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
          weight: 400